[package]
name = "matrw"
version = "0.1.4"
categories = ["parser-implementations"]
description = "MAT-file serializing and deserializing"
repository = "https://github.com/cpfist/matrw"
edition = "2024"
keywords = ["matlab", "serialization"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1"
binrw = "0.15"
chrono = "0.4"
flate2 = "1"
indexmap = "2"
serde = { version = "1", features = ["derive"], optional = true }
ndarray = { version = "0.17", optional = true }
num-complex = { version = "0.4", optional = true }

[features]
default = []
serde = ["dep:serde"]
ndarray = [
      "dep:ndarray", 
      "ndarray/serde",
      "dep:num-complex", 
      "num-complex/serde"
      ]

[dev-dependencies]
once_cell = "1"
criterion = "0.8"
which = "8"
rand = "0.10"
rand_pcg = "0.10"

[[bench]]
name = "matfile_read"
harness = false

[[bench]]
name = "matfile_write"
harness = false

